### GET Blocking Simple
GET http://localhost:8080/beverage/blocking/simple

### GET Blocking Sequential
GET http://localhost:8080/beverage/blocking/sequential

### GET Blocking Parallel
GET http://localhost:8080/beverage/blocking/parallel

### GET Reactive Single
GET http://localhost:8080/beverage/reactive/simple

### GET Reactive Sequential
GET http://localhost:8080/beverage/reactive/sequential

### GET Reactive Parallel
GET http://localhost:8080/beverage/reactive/parallel

### GET Virtual Single
GET http://localhost:8080/beverage/virtual/simple

### GET Virtual Sequential
GET http://localhost:8080/beverage/virtual/sequential

### GET Virtual Parallel
GET http://localhost:8080/beverage/virtual/parallel

### GET Structured simple
GET http://localhost:8080/beverage/structured/simple

### GET Structured custom
GET http://localhost:8080/beverage/structured/custom
