### GET Blocking Simple
GET http://localhost:8080/beverage/blocking/simple

### GET Blocking Multiple
GET http://localhost:8080/beverage/blocking/multiple

### GET Reactive Single
GET http://localhost:8080/beverage/reactive/simple

### GET Reactive Multiple
GET http://localhost:8080/beverage/reactive/multiple

### GET Virtual Single
GET http://localhost:8080/beverage/virtual/simple

### GET Virtual Multiple
GET http://localhost:8080/beverage/virtual/multiple

### GET Structured simple
GET http://localhost:8080/beverage/structured/simple

### GET Structured custom
GET http://localhost:8080/beverage/structured/custom
